- name:  Variables for prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter username
    private: false
  - name: PASSWORD
    prompt: Please enter password
    private: true
  tasks:
  - name: Entering credentials
    ansible.builtin.debug:
      msg: "{{USERNAME}},{{PASSWORD}}"



# - name: variables from prompt
#   hosts: localhost
#   vars_prompt:
#   - name: USERNAME
#     prompt: Please enter your username
#     private: false # you can see the value entered on screen
#   - name: PASSWORD
#     prompt: Please enter your password
#     private: true # you can't see the value entered on screen
#   tasks:
#   - name: print variable values
#     ansible.builtin.debug:
#       msg: "username: {{USERNAME}}, password: {{PASSWORD}}"