- name: using variables from tasks
  hosts: localhost
  vars:
  - money: "2000 rs"
    land: "150 acers"
  tasks:
  - name: Printing varibles outside
    ansible.builtin.debug:
      msg: "Money is: {{money}}, Land is: {{land}}"
    vars:
     - land: "250 acers"
      house: "3 BHK"
     - name: Printing from the variables
         ansible.builtin.debug:
          msg: "Money is: {{money}}, Land is: {{land}}, House is : {{house}}"

# - name: variables at task level
#   hosts: localhost
#   # these variables of parent or play level
#   vars:
#   - money: "10000 RS"
#     land: "100 hectars"
#   tasks:
#   - name: inherit values from play
#     ansible.builtin.debug:
#       msg: "MONEY: {{money}}, LAND: {{land}}"
#   - name: inherit values from play and add and override
#     vars:
#     - money: "200000 RS"
#       houses: "3 houses"
#     ansible.builtin.debug:
#       msg: "MONEY: {{money}}, LAND: {{land}}, houses: {{houses}}"